#!/usr/bin/env bash

# this script is shamefully generated by ChatGPT (based on GPT-5.5)
# just out of the LLM it was bugful, so it was manually reviewed and fixed

set -euo pipefail

MODE="raw"

usage() {
cat <<EOF
Usage:
  $(basename "$0") [OPTIONS] /dev/foxramdiskN
Options:
  -h         Human-readable IEC units (KiB, MiB, GiB, TiB)
  --si       Human-readable SI units (kB, MB, GB, TB)
  --help     Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h)
            MODE="iec"
            shift
            ;;
        --si)
            MODE="si"
            shift
            ;;
        --help)
            usage
            exit 0
            ;;
        -*)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [[ $# -ne 1 ]]; then
    usage >&2
    exit 1
fi

DEV_PATH="$1"
DEV_NAME="$(basename "$DEV_PATH")"

SYSFS_DIR="/sys/block/${DEV_NAME}"

if [[ ! -d "$SYSFS_DIR" ]]; then
    echo "Error: ${DEV_PATH} is not a valid block device." >&2
    exit 1
fi

read_stat() {
    cat "$1" 2>/dev/null
}

format_bytes() {
    local bytes="$1"

    case "$MODE" in
        raw)
            printf $bytes
            ;;
        iec)
            awk -v bytes="$bytes" '
            BEGIN {
                split("B KiB MiB GiB TiB PiB EiB", u, " ")
                value = bytes
                unit = 1

                while (value >= 1024 && unit < 7) {
                    value /= 1024
                    unit++
                }

                printf "%.2f %s", value, u[unit]
            }'
            ;;
        si)
            awk -v bytes="$bytes" '
            BEGIN {
                split("B kB MB GB TB PB EB", u, " ")
                value = bytes
                unit = 1

                while (value >= 1000 && unit < 7) {
                    value /= 1000
                    unit++
                }

                printf "%.2f %s", value, u[unit]
            }'
            ;;
    esac
}

IO_DIR="${SYSFS_DIR}/io_stat"
ST_DIR="${SYSFS_DIR}/storage_stat"

TOTAL_WRITTEN=$(read_stat "${IO_DIR}/total_bytes_written")
TOTAL_READ=$(read_stat "${IO_DIR}/total_bytes_read")
TOTAL_DISCARDED=$(read_stat "${IO_DIR}/total_bytes_discarded")
FAILED_READS=$(read_stat "${IO_DIR}/failed_reads")
FAILED_WRITES=$(read_stat "${IO_DIR}/failed_writes")
FAILED_DISCARDS=$(read_stat "${IO_DIR}/failed_discards")

BLOCK_SIZE=$(read_stat "${ST_DIR}/block_size")
RAW_BLOCKS=$(read_stat "${ST_DIR}/raw_blocks_count")
ZEROED_BLOCKS=$(read_stat "${ST_DIR}/zeroed_blocks_count")
COMPRESSED_BLOCKS=$(read_stat "${ST_DIR}/compressed_blocks_count")
COMPRESSED_SIZE=$(read_stat "${ST_DIR}/compressed_data_size")
COMPRESSION_NAME=$(read_stat "${ST_DIR}/compression_name")

RAW_SIZE=$((RAW_BLOCKS * BLOCK_SIZE))
ZEROED_SIZE=$((ZEROED_BLOCKS * BLOCK_SIZE))
COMPRESSED_LOGICAL_SIZE=$((COMPRESSED_BLOCKS * BLOCK_SIZE))

COMPRESSED_ONLY_RATIO="N/A"
EFFECTIVE_RATIO="N/A"

if [[ "$COMPRESSED_SIZE" -gt 0 ]]; then
    COMPRESSED_ONLY_RATIO=$(echo "$COMPRESSED_LOGICAL_SIZE / $COMPRESSED_SIZE" | bc -lq)
    EFFECTIVE_RATIO=$(echo "($COMPRESSED_LOGICAL_SIZE + $RAW_SIZE) / ($COMPRESSED_SIZE + $RAW_SIZE)" | bc -lq)
    COMPRESSED_ONLY_RATIO=$(printf "%.3f" $COMPRESSED_ONLY_RATIO)
    EFFECTIVE_RATIO=$(printf "%.3f" $EFFECTIVE_RATIO)
fi

printf "%-32s %s\n" "Bytes written:" "$(format_bytes "$TOTAL_WRITTEN")"
printf "%-32s %s\n" "Bytes read:" "$(format_bytes "$TOTAL_READ")"
printf "%-32s %s\n" "Bytes discarded:" "$(format_bytes "$TOTAL_DISCARDED")"
printf "%-32s %s\n" "Failed reads:" "$FAILED_READS"
printf "%-32s %s\n" "Failed writes:" "$FAILED_WRITES"
printf "%-32s %s\n" "Failed discards:" "$FAILED_DISCARDS"

echo

printf "%-32s %s\n" "Block size in bytes:" "$BLOCK_SIZE"
printf "%-32s %s\n" "Incompressible blocks:" "$RAW_BLOCKS"
printf "%-32s %s\n" "Incompressible blocks data size:" "$(format_bytes "$RAW_SIZE")"
printf "%-32s %s\n" "Zeroed blocks:" "$ZEROED_BLOCKS"
printf "%-32s %s\n" "Zeroed blocks logical size:" "$(format_bytes "$ZEROED_SIZE")"
printf "%-32s %s\n" "Compressed blocks:" "$COMPRESSED_BLOCKS"
printf "%-32s %s\n" "Compressed blocks logical size:" "$(format_bytes "$COMPRESSED_LOGICAL_SIZE")"
printf "%-32s %s\n" "Compressed data size:" "$(format_bytes "$COMPRESSED_SIZE")"

echo

if [[ "$COMPRESSION_NAME" == "nocomp" ]]; then
    echo "Compression is disabled for this device."
else
    printf "%-32s %s\n" "Compression algorithm: " $COMPRESSION_NAME
fi

echo
printf "%-32s %s\n" "Compression ratio:" "$COMPRESSED_ONLY_RATIO"
echo "    Incompressible blocks are not considered."
printf "%-32s %s\n" "Effective compression ratio:" "$EFFECTIVE_RATIO"
echo "    Incompressible blocks are treated as compression ratio 1:1."
